name: Validate OpenAPI Spec

on:
  pull_request:
    paths:
      - "api/meta/meta.yaml"
      - "api/registry/registry.yaml"
      - "api/transaction/transaction.yaml"

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install openapi-cli
        run: npm install -g @redocly/cli

      - name: Validate OpenAPI files
        run: ./validate-openapi.sh
