name: CI

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
    paths:
      - "api/meta/build/meta.yaml"
      - "api/registry/build/registry.yaml"
      - "api/transaction/build/transaction.yaml"

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install openapi-cli
        run: npm install -g @redocly/cli

      - name: Make script executable
        run: chmod +x ./validate-openapi.sh

      - name: Validate OpenAPI files
        run: ./validate-openapi.sh
